[supervisord]
nodaemon=true
user=root
logfile=/app/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:binance_new_coin_detector]
command=python /app/binance/binance_new_coin_download.py
directory=/app/binance
autostart=true
autorestart=true
stderr_logfile=/app/logs/binance_new_coin_detector.err.log
stdout_logfile=/app/logs/binance_new_coin_detector.out.log
environment=PYTHONPATH="/app:/app/binance:/app/okx"

[program:okx_new_coin_detector]
command=python /app/okx/okx_new_coins_downloader.py
directory=/app/okx
autostart=true
autorestart=true
stderr_logfile=/app/logs/okx_new_coin_detector.err.log
stdout_logfile=/app/logs/okx_new_coin_detector.out.log
environment=PYTHONPATH="/app:/app/binance:/app/okx"

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
